services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_SCHEMA: kairos_politica
      SECRET_KEY: ${SECRET_KEY}
      KAIROS_ADMIN_URL: https://api.admin.fbautomacao.space
      KAIROS_CLIENT_ID: ${KAIROS_CLIENT_ID}
      KAIROS_ADMIN_BASIC_USER: ${KAIROS_ADMIN_BASIC_USER}
      KAIROS_ADMIN_BASIC_PASSWORD: ${KAIROS_ADMIN_BASIC_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8021:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3041:80"
